### ISSUE TITLE
[Question] XS-3868 connect to arduino.

### ISSUE THREAD

**Issue by AYastrebov** [tomaskovacik/vwcdavr#1]
Hello, Tomas!

Nice work!
I've successfully flashed arduino pro mini and now have an AUX in my vw sony gamma 5.

I've purchased XS-3868 board and would like to use it in my system. But unfortunately, I can't figure out, which pins of XS-3868 should be connected to arduino board. Can you point me?

Thanks!

**Comment by tomaskovacik** [comment]
Look in my hw repository. Kicad and there are modules with pinouts also schemarics for arduino and bluethooth

Sent from my Sony Xperia™ smartphone

---- Andrey Yastrebov wrote ----
