### ISSUE TITLE
No CDC detected using ATtiny85

### ISSUE THREAD

**Issue by lachaka** [tomaskovacik/vwcdavr#12]
Hi,
I can not simulate a CDC using the "cdc_arduino_ported_k9spud_vwcdpic_just_8bit_timers" version. On the serial monitor I got only the welcome text and the radio says " No CDC". The other version works fine, tested with atmega328.
Tried to slap Clk and Data in, but still no result.

**Comment by tomaskovacik** [comment]
attiny85 at 8MHz ?

**Comment by lachaka** [comment]
yep

**Comment by tomaskovacik** [comment]
try this sketch on atmega328

**Comment by lachaka** [comment]
Nothing happens, I even don't get "No CDC"

**Comment by tomaskovacik** [comment]
try uncoment //_delay_loop_1(40); on lines 1134 and 1158

**Comment by lachaka** [comment]
Now on atmega328 is working, on attiny is the same

**Comment by tomaskovacik** [comment]
are you using HW pin 7,6 and 5 ? 
   DataOut   -> 7 (INT0)
   DataIn    -> 6 (PB0)
   Clock     -> 5 (PB1)

**Comment by lachaka** [comment]
Yes, but pin 5 is PB0 and 6 is PB1. Anyway after slapping still not success.

**Comment by tomaskovacik** [comment]
yep, pb0 is 5, but it strange, anyway I cannot help you more right now, I will test it tomorow
t.

**Comment by lachaka** [comment]
No worries. When the radio is powered off I got "00" dataerr and on powering it up another ones but a little bit different, if helpful.

**Comment by tomaskovacik** [comment]
I just test code as it was  (no delay when clocking out data) and it works without problem, but I put defined 5microseconds delay there so it is same as 3timer version. Anyway,here is output:
![image](https://user-images.githubusercontent.com/4346464/94523017-dcbd2080-0230-11eb-8b0f-2c7a7c9c11d9.png)

**Comment by tomaskovacik** [comment]
![20200929_085140.jpg](https://user-images.githubusercontent.com/4346464/94523107-01b19380-0231-11eb-8469-5d23ef2b70c9.jpg)

**Comment by lachaka** [comment]
Now the CDC is detected and I got all six CDs, but after clicking two or three times any button the radio blocks and got dataerr in serial monitor. Maybe some other delays are needed.

**Comment by tomaskovacik** [comment]
and what you did exactly? , as you can see I got to track 15 so -> 30 commands, got through.

you can play with CLK_DELAY value

lot of times, bad ground connection is problem. check that also
