### ISSUE TITLE
arduino uno

### ISSUE THREAD

**Issue by JL01152** [tomaskovacik/vwcdavr#4]
I keep getting an error message of "PB0 was not declared in this scope." I am using an Arduino Uno and Arduino IDE I'm at a loss as to what the issue may be. Please Help.

**Comment by tomaskovacik** [comment]
which sketch?

**Comment by tomaskovacik** [comment]
I try all sketches in this repo, on arduino 1.8.5 everyone compile fine for arduino uno, closing
